### ISSUE TITLE
Don't require audio - crashes if audio device not found

### ISSUE THREAD

**Issue by yonas** [JonathanMurray/tiny-games#1]
It would be great to play games over ssh without audio.

Edit:

It works when I run `cargo run -- --runtime terminal tetris`, but breaks if I run `terminal-games tetris`. Can we put an exception handler to catch the error and carry on without audio?

**Comment by JonathanMurray** [comment]
Hey, that's interesting. I agree that an audio device should not be required. Cool idea to run over SSH! That's not something I'd thought about.

When you omit the `--runtime terminal` flag you get the default `window` runtime which uses [ggez](https://docs.rs/ggez/latest/ggez/index.html) to bring up a graphics window. Are you doing something like `ssh -X` to forward the graphics from the remote host? I assume a regular `ssh` wouldn't work, even if there weren't any audio device issues (?)

Could you paste the exact error (full stacktrace preferably) you're getting so I can try to see what it is inside `ggez` that might trigger it?

**Comment by yonas** [comment]
> Are you doing something like ssh -X to forward the graphics from the remote host? I assume a regular ssh wouldn't work, even if there weren't any audio device issues (?)

I'm running ssh without forwarding. The graphics work well over regular ssh.

![Screenshot from 2022-11-05 16-19-05](https://user-images.githubusercontent.com/110130/200139349-5fcb3e3e-e970-430d-a20e-412a3b867fad.png)

```
RUST_BACKTRACE=full target/release/terminal-games snake
ALSA lib dlmisc.c:285:(snd_dlobj_cache_get0) Cannot open shared library /usr/local/lib/alsa-lib/libasound_module_pcm_oss.so ((null): Cannot open "/usr/local/lib/alsa-lib/libasound_module_pcm_oss.so")
ALSA lib dlmisc.c:285:(snd_dlobj_cache_get0) Cannot open shared library /usr/local/lib/alsa-lib/libasound_module_pcm_oss.so ((null): Cannot open "/usr/local/lib/alsa-lib/libasound_module_pcm_oss.so")
ALSA lib dlmisc.c:285:(snd_dlobj_cache_get0) Cannot open shared library /usr/local/lib/alsa-lib/libasound_module_pcm_oss.so ((null): Cannot open "/usr/local/lib/alsa-lib/libasound_module_pcm_oss.so")
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AudioError("Could not initialize sound system using default output device (for some reason)")', src/ui/window.rs:32:10
stack backtrace:
   0:     0x2827e5cfebac - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf9bca0a54f465bd9
   1:     0x2827e5d16e0e - core::fmt::write::hdf9e1b7bc0c7ef23
   2:     0x2827e5cd6e91 - std::io::Write::write_fmt::h6e00616d8cf5d394
   3:     0x2827e5ce87f5 - std::panicking::default_hook::{{closure}}::ha5a1e37665f439d8
   4:     0x2827e5ce845e - std::panicking::default_hook::h791a251cba6fed5f
   5:     0x2827e5ce8e08 - std::panicking::rust_panic_with_hook::h184324b56212ec2b
   6:     0x2827e5cff5d7 - std::panicking::begin_panic_handler::{{closure}}::hdd7dccc960a25e4f
   7:     0x2827e5cfecc4 - std::sys_common::backtrace::__rust_end_short_backtrace::h1fb3000d64dd03f0
   8:     0x2827e5ce8ab2 - rust_begin_unwind
   9:     0x2827e5d19643 - core::panicking::panic_fmt::hc3aba48bba555f86
  10:     0x2827e5d1bb93 - core::result::unwrap_failed::hb64f9d366cb13a63
  11:     0x2827e560bc75 - core::result::Result<T,E>::unwrap::h0a213135bf17ad29
  12:     0x2827e560d99a - terminal_games::ui::window::run_main_loop::hb0d28c32175cceff
  13:     0x2827e55e41d0 - terminal_games::main::h9c0bd2176e0bbf18
  14:     0x2827e563b7f3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h76785d293ed1cc1b
  15:     0x2827e563ba49 - std::rt::lang_start::{{closure}}::h3cb10c6997becd05
  16:     0x2827e5cd5d91 - std::rt::lang_start_internal::h1d0782bd0a0efa37
  17:     0x2827e55e58f2 - main

```

**Comment by JonathanMurray** [comment]
Thanks for the log output! The error arises when `ggez` tries to initialise the window, so it's not one that we can simply ignore on our end and continue: https://github.com/ggez/ggez/blob/0601efee5f6d53ad1326e7fc68ebc06d218c4a1a/src/context.rs#L175

However, it seems that the audio functionality of ggez is opt-in by a feature-flag (but that flag is enabled by default when importing the library, so I got it without really thinking about it). Could you check if this change solves it for you? https://github.com/JonathanMurray/tiny-games/pull/2

**Comment by yonas** [comment]
Thanks @JonathanMurray, it got me past that error.

As it's still running in windows mode by default, it's crashed on another X11 dependency:

```
RUST_BACKTRACE=full target/release/terminal-games snake
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: XdgRuntimeDirNotSet X11 status: LibraryOpenError(OpenError { kind: Library, detail: "opening library failed (Shared object \"libXcursor.so.1\" not found, required by \"terminal-games\"); opening library failed (Shared object \"libXcursor.so\" not found, required by \"terminal-games\")" })', /home/yonas/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/mod.rs:719:9
stack backtrace:
   0:      0xbd3d534f1ec - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf9bca0a54f465bd9
   1:      0xbd3d536737e - core::fmt::write::hdf9e1b7bc0c7ef23
   2:      0xbd3d53276d1 - std::io::Write::write_fmt::h6e00616d8cf5d394
   3:      0xbd3d5338e65 - std::panicking::default_hook::{{closure}}::ha5a1e37665f439d8
   4:      0xbd3d5338ace - std::panicking::default_hook::h791a251cba6fed5f
   5:      0xbd3d5339478 - std::panicking::rust_panic_with_hook::h184324b56212ec2b
   6:      0xbd3d534fc17 - std::panicking::begin_panic_handler::{{closure}}::hdd7dccc960a25e4f
   7:      0xbd3d534f304 - std::sys_common::backtrace::__rust_end_short_backtrace::h1fb3000d64dd03f0
   8:      0xbd3d5339122 - rust_begin_unwind
   9:      0xbd3d5369b73 - core::panicking::panic_fmt::hc3aba48bba555f86
  10:      0xbd3d4e1ff44 - winit::platform_impl::platform::EventLoop<T>::new::h1920f192b4473a16
  11:      0xbd3d4e16501 - ggez::context::ContextBuilder::build::hc0938bee51723d21
  12:      0xbd3d4cdd745 - terminal_games::ui::window::run_main_loop::h325f9688f6eba05a
  13:      0xbd3d4caa4b2 - terminal_games::main::haa4cefe0d45101bd
  14:      0xbd3d4c9bdd3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc1e1a04b8b98a89f
  15:      0xbd3d4cabba9 - std::rt::lang_start::{{closure}}::h536640d55f750724
  16:      0xbd3d53265d1 - std::rt::lang_start_internal::h1d0782bd0a0efa37
  17:      0xbd3d4cabb92 - main
```

**Comment by JonathanMurray** [comment]
The plot thickens... `ggez` internally uses `winit` for some of the graphics stuff and that's where this error comes from: https://github.com/rust-windowing/winit/blob/v0.27.5/src/platform_impl/linux/mod.rs#L719

I should preface this by saying that my knowledge about X11 and Wayland is quite limited. Anyway, as I understand it, to be able to run graphical applications over SSH you need to be using either X11 or Wayland (or some other "display protocol"). `winit` apparently tries both, in sequence, but ultimately fails and reports the following failure reasons:

* Wayland: `XdgRuntimeDirNotSet`
* X11: `[...] Shared object \"libXcursor.so.1\" not found`

What I can find about the Wayland error is: https://docs.rs/wayland-client/latest/wayland_client/enum.ConnectError.html#variant.XdgRuntimeDirNotSet. Apparently there's an environment variable `XDG_RUNTIME_DIR` that some code wants to be set but isn't. I've never heard of it before, but there's some interesting discussion of it [here](https://askubuntu.com/questions/872792/what-is-xdg-runtime-dir).

To understand the X11 error I think more info about your environment might be necessary.

I return to my earlier point about `ssh -X`, though. If I understand your comments correctly, you haven't actually been able to get any `window` graphics through SSH (but rather just `terminal` graphics). My understanding is that you may need to use the `-X` flag (`Enables X11 forwarding`) in order to to bring up an actual graphical application window over SSH (i.e. not just displaying text-based graphics as in your earlier screenshot).

**Comment by yonas** [comment]
> I return to my earlier point about ssh -X, though. If I understand your comments correctly, you haven't actually been able to get any window graphics through SSH (but rather just terminal graphics). My understanding is that you may need to use the -X flag (Enables X11 forwarding) in order to to bring up an actual graphical application window over SSH (i.e. not just displaying text-based graphics as in your earlier screenshot).

Yes, that's correct. I did not use `ssh -X` because I don't want to use X11, just terminal graphics.

**Comment by JonathanMurray** [comment]
> I don't want to use X11, just terminal graphics.

Then I'm afraid I don't understand what this issue is about.

> It works when I run cargo run -- --runtime terminal tetris

That is the intended mechanism for picking terminal graphics. You wrote in the initial post:

> It would be great to play games over ssh without audio.

It sounds like you _are_ able to play games over ssh without audio. Unless there's some misunderstanding here, I'm gonna go ahead and close this issue :)

**Comment by yonas** [comment]
# Problem

As an end user, why do we need to explicitly choose between terminal and window graphics?

# Proposed Solution
The program should initialize as follows - if window mode does not successfully initialize, the program would automatically try terminal mode instead of crashing.

If the default mode is window, I'm proposing that terminal mode be the fallback. This would mean I don't have to explicitly mention which graphics mode.

**Comment by JonathanMurray** [comment]
Ah! Now I understand. That sounds like a good solution to me. I'll look into it later, or feel free to make a PR yourself, if you want!

**Comment by JonathanMurray** [comment]
Since the error from the library is a `panic` catching it is a bit cumbersome. Instead I'll just change the default from `window` to `terminal`. That's probably a better default anyway, considered how the project is presented.

---

Solved by https://github.com/JonathanMurray/tiny-games/pull/3 @yonas Thanks for trying out the games and raising this inconvenience!
